SELECT C.ID, C.NAME, COUNT(P.ID) AS PROJECT_COUNT
FROM CLIENT C
JOIN PROJECT P ON C.ID=P.CLIENT_ID
GROUP BY C.ID, C.NAME
HAVING COUNT(P.ID) = (SELECT MAX(PROJECT_COUNT) FROM (SELECT CLIENT_ID, COUNT(ID) AS PROJECT_COUNT FROM PROJECT GROUP BY CLIENT_ID ) AS T);