WITH ProjectCost AS (
    SELECT
        P.ID AS PROJECT_ID,
        
        SUM(W.SALARY * (P.START_DATE-P.FINISH_DATE)) AS PROJECT_PRICE
    FROM
        PROJECT P
    JOIN
        PROJECT_WORKER PW ON P.ID = PW.PROJECT_ID
    JOIN
        WORKER W ON PW.WORKER_ID = W.ID
    GROUP BY
        P.ID
)

SELECT
    PROJECT_ID AS NAME,
    PROJECT_PRICE AS PRICE
FROM
    ProjectCost
ORDER BY
    PROJECT_PRICE DESC;